// Every iOS plugin has to be CocoaPods-compatible.
//
// The iOS pipeline pins CocoaPods — `flutter config --no-enable-swift-package
// -manager` in .github/workflows/ios-release.yml, because that is the path the
// release was verified on. A dependency that ships only a Package.swift and no
// podspec therefore cannot build, and Flutter refuses it at `pub get` with
// "Plugin X is only Swift Package Manager compatible".
//
// That refusal happens on macOS only. On Windows and Linux the iOS tooling
// never runs, so `flutter pub get`, `flutter analyze`, the whole test suite and
// an Android release build all pass with the broken dependency in place, and
// the first thing to notice is the release job — after the tag is cut. That is
// how app_settings reached a tagged release.
//
// This is the same check, run where the work happens.

import 'dart:convert';
import 'dart:io';

import 'package:flutter_test/flutter_test.dart';

void main() {
  test('no iOS plugin depends on Swift Package Manager', () {
    // Generated by `flutter pub get`; it is what the iOS build reads.
    final manifest = File('.flutter-plugins-dependencies');
    expect(manifest.existsSync(), isTrue,
        reason: 'run flutter pub get first');

    final json =
        jsonDecode(manifest.readAsStringSync()) as Map<String, dynamic>;

    // If the pipeline ever switches to SPM this test is obsolete rather than
    // wrong — so it checks the assumption it is built on, and says so.
    final spm = (json['swift_package_manager_enabled'] as Map?)?['ios'];
    if (spm == true) {
      markTestSkipped('SPM is enabled for iOS; podspecs are no longer required');
      return;
    }

    final plugins = ((json['plugins'] as Map)['ios'] as List)
        .cast<Map<String, dynamic>>();
    expect(plugins, isNotEmpty, reason: 'the app does use iOS plugins');

    final spmOnly = <String>[];
    for (final plugin in plugins) {
      // A plugin with no native build needs no podspec — path_provider_
      // foundation is pure Dart now and ships no darwin sources at all. Only
      // the ones that actually compile something have to package it.
      if (plugin['native_build'] == false) continue;
      final dir = Directory(plugin['path'] as String);
      if (!dir.existsSync()) continue; // Not resolved on this machine.
      final hasPodspec = dir
          .listSync(recursive: true, followLinks: false)
          .whereType<File>()
          .any((f) => f.path.endsWith('.podspec'));
      if (!hasPodspec) spmOnly.add(plugin['name'] as String);
    }

    expect(spmOnly, isEmpty,
        reason: 'these ship no podspec, so the iOS release job will fail at '
            'pub get before it builds anything: ${spmOnly.join(', ')}');
  });
}
