// Game Center on iOS, Play Games Services on Android.
//
// Both platforms are wired up. The iOS column holds the reverse-domain ids
// registered in App Store Connect, the Android column the generated Play
// Console ones, and all ten exist on both sides.
//
// The plugin's Achievement.id returns androidID on Android, so a blank one
// would hand Play Games an empty achievement id. [_unlock] still refuses to
// send one, which is now a safety net against a half-filled table rather than
// the state the app ships in.
//
// Everything here is optional and fire-and-forget. A player who never signs in,
// declines Game Center, or plays offline must see no difference in the game, so
// nothing is awaited from game code and every call swallows its errors. An
// achievement is a nice thing that happens, never a thing that can fail.

import 'dart:async';
import 'dart:io' show Platform;

import 'package:flutter/foundation.dart';
import 'package:games_services/games_services.dart';

import 'cloud_save_service.dart';

/// The achievements Dotto reports, with their per-platform ids.
///
/// iOS uses the reverse-domain ids registered in App Store Connect. The Android
/// column is filled in from the Play Console, where ids look like
/// `CgkI...ABw` — they are generated, not chosen, so they cannot be written
/// ahead of the console work.
class _Ach {
  const _Ach(this.ios, this.android);

  final String ios;
  final String android;

  String get forPlatform => Platform.isAndroid ? android : ios;
}

// The Android ids are generated by Play Console and are meaningless to read —
// they differ only in their last character or two, so a transposition here
// would silently unlock the wrong badge rather than fail. Kept in the same
// order as the worlds for that reason, and covered by a test that checks they
// are all distinct.
const _worldAchievements = <int, _Ach>{
  1: _Ach('com.karimkod.dotto.world1', 'CgkIq9GejqIREAIQAA'),
  2: _Ach('com.karimkod.dotto.world2', 'CgkIq9GejqIREAIQAQ'),
  3: _Ach('com.karimkod.dotto.world3', 'CgkIq9GejqIREAIQAg'),
  4: _Ach('com.karimkod.dotto.world4', 'CgkIq9GejqIREAIQAw'),
  5: _Ach('com.karimkod.dotto.world5', 'CgkIq9GejqIREAIQBA'),
  6: _Ach('com.karimkod.dotto.world6', 'CgkIq9GejqIREAIQBQ'),
  7: _Ach('com.karimkod.dotto.world7', 'CgkIq9GejqIREAIQBg'),
};

const _master = _Ach('com.karimkod.dotto.master', 'CgkIq9GejqIREAIQBw');
const _hintSeeker = _Ach('com.karimkod.dotto.hint_seeker', 'CgkIq9GejqIREAIQCA');
const _speedRunner = _Ach('com.karimkod.dotto.speed_runner', 'CgkIq9GejqIREAIQCQ');

/// Hints taken across all sessions before "Hint Seeker" unlocks.
const int kHintSeekerTarget = 10;

/// Levels finished in one sitting before "Speed Runner" unlocks.
const int kSpeedRunnerTarget = 5;

class GameServices {
  GameServices._();

  /// Whether the Android side is configured well enough to sign in.
  ///
  /// True since the Play Games application id landed in AndroidManifest.xml
  /// (as `@string/app_id`, defined in res/values/games-ids.xml). That entry is
  /// what this gate was waiting for: the SDK fails as it starts without one,
  /// natively, which the try/catch around [signIn] would not contain.
  ///
  /// If Android sign-in ever needs disabling in a hurry — a crash on some
  /// device, a Play Console misconfiguration — setting this back to false is
  /// the switch, and costs nothing but the achievements.
  static const bool _androidReady = true;

  /// Where a games platform exists to talk to. Web has none, and `flutter test`
  /// has no plugin host.
  static bool get supported {
    if (kIsWeb) return false;
    if (Platform.environment.containsKey('FLUTTER_TEST')) return false;
    if (Platform.isAndroid) return _androidReady;
    return Platform.isIOS;
  }

  static bool _signedIn = false;
  static bool get signedIn => _signedIn;

  /// Levels finished since launch, for Speed Runner. Not persisted — the
  /// achievement is about one sitting.
  static int _sessionCompletions = 0;

  /// Sign in quietly. No UI on failure: a player who has never opened Game
  /// Center should not be met with an error about a feature they did not ask
  /// for.
  static Future<void> signIn() async {
    if (!supported) return;
    try {
      await GamesServices.signIn();
      _signedIn = await GamesServices.isSignedIn;
    } catch (e) {
      debugPrint('Game services sign-in failed, achievements off: $e');
      return;
    }
    // Saved games are per-account, so the cloud is only reachable once there is
    // an account. This is the earliest honest moment to pull it.
    if (_signedIn) await CloudSaveService.load();
  }

  /// Open the platform's own achievements screen.
  ///
  /// Returns false when there is nothing to show — not signed in, or no games
  /// platform — so the caller can keep the entry point out of the way rather
  /// than opening nothing.
  static Future<bool> showAchievements() async {
    if (!supported || !_signedIn) return false;
    try {
      await GamesServices.showAchievements();
      return true;
    } catch (e) {
      debugPrint('Could not show achievements: $e');
      return false;
    }
  }

  static void _unlock(_Ach ach) {
    if (!supported || !_signedIn) return;
    // Sending a blank id would be an error report per achievement, several
    // times a level. Every id is filled in now, so this only ever fires if one
    // is removed again.
    if (ach.forPlatform.isEmpty) return;
    unawaited(
      GamesServices.unlock(
        achievement: Achievement(
          androidID: ach.android,
          iOSID: ach.ios,
          percentComplete: 100,
        ),
      ).catchError((Object e) {
        debugPrint('Achievement unlock failed: $e');
        return null;
      }),
    );
  }

  /// Called after a level is recorded as complete.
  ///
  /// [completed] is the full set of finished levels, [world] the world the
  /// level just won belongs to, and [worldFinished] whether that world is now
  /// complete. The caller works those out because it already holds the level
  /// data; this class deliberately knows nothing about level numbering.
  static void onLevelCompleted({
    required int world,
    required bool worldFinished,
    required int totalCompleted,
    required int levelCount,
    required int lifetimeHints,
  }) {
    if (!supported) return;

    _sessionCompletions++;
    if (_sessionCompletions >= kSpeedRunnerTarget) _unlock(_speedRunner);

    if (worldFinished) {
      final ach = _worldAchievements[world];
      if (ach != null) _unlock(ach);
    }
    if (totalCompleted >= levelCount) _unlock(_master);
    if (lifetimeHints >= kHintSeekerTarget) _unlock(_hintSeeker);
  }

  /// Hints are taken outside a level completion too, so this is checked on its
  /// own as well — otherwise the badge would wait for the next level to end.
  static void onHintUsed(int lifetimeHints) {
    if (lifetimeHints >= kHintSeekerTarget) _unlock(_hintSeeker);
  }

  /// Tests only.
  @visibleForTesting
  static void resetForTest() {
    _sessionCompletions = 0;
    _signedIn = false;
  }

  /// Tests only: every (iOS, Android) id pair the game can report.
  @visibleForTesting
  static List<(String, String)> get allIds => [
        for (final a in _worldAchievements.values) (a.ios, a.android),
        (_master.ios, _master.android),
        (_hintSeeker.ios, _hintSeeker.android),
        (_speedRunner.ios, _speedRunner.android),
      ];

  /// Tests only: whether Android is switched on yet.
  @visibleForTesting
  static bool get androidReady => _androidReady;
}
