// Game Center on iOS, Play Games Services on Android.
//
// Both platforms are wired up. The iOS column holds the reverse-domain ids
// registered in App Store Connect, the Android column the generated Play
// Console ones, and all ten exist on both sides.
//
// The plugin's Achievement.id returns androidID on Android, so a blank one
// would hand Play Games an empty achievement id. [_unlock] still refuses to
// send one, which is now a safety net against a half-filled table rather than
// the state the app ships in.
//
// Everything here is optional and fire-and-forget. A player who never signs in,
// declines Game Center, or plays offline must see no difference in the game, so
// nothing is awaited from game code and every call swallows its errors. An
// achievement is a nice thing that happens, never a thing that can fail.

import 'dart:async';
import 'dart:convert' show base64Decode;
import 'dart:io' show Platform;

import 'package:flutter/foundation.dart';
import 'package:games_services/games_services.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'cloud_save_service.dart';

/// The achievements Dotto reports, with their per-platform ids.
///
/// iOS uses the reverse-domain ids registered in App Store Connect. The Android
/// column is filled in from the Play Console, where ids look like
/// `CgkI...ABw` — they are generated, not chosen, so they cannot be written
/// ahead of the console work.
class _Ach {
  const _Ach(this.ios, this.android);

  final String ios;
  final String android;

  String get forPlatform => Platform.isAndroid ? android : ios;
}

// The Android ids are generated by Play Console and are meaningless to read —
// they differ only in their last character or two, so a transposition here
// would silently unlock the wrong badge rather than fail. Kept in the same
// order as the worlds for that reason, and covered by a test that checks they
// are all distinct.
const _worldAchievements = <int, _Ach>{
  1: _Ach('com.karimkod.dotto.world1', 'CgkIq9GejqIREAIQAA'),
  2: _Ach('com.karimkod.dotto.world2', 'CgkIq9GejqIREAIQAQ'),
  3: _Ach('com.karimkod.dotto.world3', 'CgkIq9GejqIREAIQAg'),
  4: _Ach('com.karimkod.dotto.world4', 'CgkIq9GejqIREAIQAw'),
  5: _Ach('com.karimkod.dotto.world5', 'CgkIq9GejqIREAIQBA'),
  6: _Ach('com.karimkod.dotto.world6', 'CgkIq9GejqIREAIQBQ'),
  7: _Ach('com.karimkod.dotto.world7', 'CgkIq9GejqIREAIQBg'),
};

const _master = _Ach('com.karimkod.dotto.master', 'CgkIq9GejqIREAIQBw');
const _hintSeeker = _Ach('com.karimkod.dotto.hint_seeker', 'CgkIq9GejqIREAIQCA');
const _speedRunner = _Ach('com.karimkod.dotto.speed_runner', 'CgkIq9GejqIREAIQCQ');

/// Hints taken across all sessions before "Hint Seeker" unlocks.
const int kHintSeekerTarget = 10;

/// Levels finished in one sitting before "Speed Runner" unlocks.
const int kSpeedRunnerTarget = 5;

/// The signed-in player as the platform describes them: their gamer tag and
/// their avatar, already decoded into something [Image.memory] will take.
///
/// Both fields are independently optional. Play Games hands back a display name
/// for everyone but keeps the avatar behind the player's own privacy settings,
/// so a profile with a name and no picture is ordinary rather than a failure.
class PlayerProfile {
  const PlayerProfile({this.name, this.icon});

  /// The gamer tag, or null when the platform gave a blank one.
  final String? name;

  /// The icon-sized profile picture, or null when there is none to show.
  final Uint8List? icon;
}

class GameServices {
  GameServices._();

  /// Whether the Android side is configured well enough to sign in.
  ///
  /// True since the Play Games application id landed in AndroidManifest.xml
  /// (as `@string/app_id`, defined in res/values/games-ids.xml). That entry is
  /// what this gate was waiting for: the SDK fails as it starts without one,
  /// natively, which the try/catch around [ensureSignedIn] would not contain.
  ///
  /// If Android sign-in ever needs disabling in a hurry — a crash on some
  /// device, a Play Console misconfiguration — setting this back to false is
  /// the switch, and costs nothing but the achievements.
  static const bool _androidReady = true;

  /// Where a games platform exists to talk to. Web has none, and `flutter test`
  /// has no plugin host.
  static bool get supported {
    if (kIsWeb) return false;
    if (Platform.environment.containsKey('FLUTTER_TEST')) return false;
    if (Platform.isAndroid) return _androidReady;
    return Platform.isIOS;
  }

  static bool _signedIn = false;
  static bool get signedIn => _signedIn;

  /// Whether the onboarding sign-in offer has been made.
  ///
  /// Asked once, on a first launch, and never again: a player who declined has
  /// answered, and asking each launch is how an optional feature turns into a
  /// nuisance. Settings → Achievements is the way back in.
  static const _promptedKey = 'sign_in_prompted';

  /// Whether the player has ever signed in successfully.
  ///
  /// Written from [ensureSignedIn], read back at launch. Without it, "are we
  /// signed in?" has to be re-derived from [GamesServices.isSignedIn] on every
  /// launch — and that probe is the one thing here that cannot be relied on
  /// (see [restoreSignInState]), so a bad answer meant being asked to sign in
  /// all over again.
  static const _signedInKey = 'signed_in';
  static SharedPreferences? _prefs;
  static bool _prompted = false;

  /// Whether onboarding should offer to sign in. False once asked, once signed
  /// in, or where there is no games platform to sign in to.
  ///
  /// The router holds the offer further, until the consent question is
  /// settled — see `ConsentManager.consentSettled` and main.dart's
  /// `_afterConsent` — so this getter answering true is necessary but not
  /// sufficient for the screen to appear.
  static bool get needsSignInPrompt => supported && !_prompted && !_signedIn;

  /// Load the "already asked" and "already signed in" flags. Call before the
  /// first frame.
  static Future<void> init() async {
    try {
      final prefs = _prefs = await SharedPreferences.getInstance();
      _prompted = prefs.getBool(_promptedKey) ?? false;
      _signedIn = supported && (prefs.getBool(_signedInKey) ?? false);
    } catch (_) {
      // No storage. The offer may be made twice, which is a nuisance rather
      // than a fault.
    }
  }

  /// Remember that the offer was made — whatever the player answered.
  static void markSignInPrompted() {
    _prompted = true;
    _write(_promptedKey, true);
  }

  static void _setSignedIn(bool value) {
    _signedIn = value;
    _write(_signedInKey, value);
  }

  static void _write(String key, bool value) {
    final prefs = _prefs;
    if (prefs == null) return;
    unawaited(prefs.setBool(key, value).catchError((_) => false));
  }

  /// Levels finished since launch, for Speed Runner. Not persisted — the
  /// achievement is about one sitting.
  static int _sessionCompletions = 0;

  /// Pick up an account that already exists, without asking for one.
  ///
  /// Deliberately not a sign-in: it only reads the current state. Signing in is
  /// something the player does — from the onboarding offer or from Achievements
  /// — and a launch that raises the platform's sign-in dialog on its own is the
  /// bug this replaced.
  ///
  /// This can only ever turn sign-in *on*, never off. [GamesServices.isSignedIn]
  /// is not the simple query it looks like: it opens a subscription on the
  /// player event channel and resolves on the first thing that arrives, and a
  /// slow account fetch, a cold start where Play Games has not finished its own
  /// automatic sign-in, or no network all arrive as "not signed in". Letting
  /// that demote the flag written by a real sign-in is what put the player back
  /// in front of the prompt. It is also why this is given a deadline — the
  /// underlying future has no timeout of its own and simply never completes if
  /// the platform stays silent.
  static Future<void> restoreSignInState() async {
    if (!supported || _signedIn) {
      // Already known signed in from storage — the cloud pull still belongs to
      // this launch.
      if (_signedIn) await CloudSaveService.load();
      return;
    }
    bool live;
    try {
      live = await GamesServices.isSignedIn
          .timeout(const Duration(seconds: 10), onTimeout: () => false);
    } catch (e) {
      debugPrint('Game services state unreadable, achievements off: $e');
      return;
    }
    if (!live) return;
    _setSignedIn(true);
    // Saved games are per-account, so the cloud is only reachable once there is
    // an account. This is the earliest honest moment to pull it.
    await CloudSaveService.load();
  }

  /// The signed-in player's gamer tag and avatar, or null when there is nobody
  /// to describe.
  ///
  /// Never signs anybody in: this is what a screen the player opened to look at
  /// themselves is made of, so raising the platform's account picker here would
  /// be the same ambush [restoreSignInState] exists to avoid. The profile screen
  /// offers a Sign In button instead, and that tap is a player action.
  ///
  /// Read straight off the player stream rather than through
  /// [Player.getPlayerName] and [Player.getPlayerIconImage]. Those two are
  /// wrappers around this same stream and each opens its own subscription, so
  /// asking for a name and a picture separately is two platform round trips for
  /// one record that arrives with both fields already on it.
  ///
  /// Given a deadline for the same reason [restoreSignInState] is: the stream
  /// simply stays silent when the platform has nothing to say, so the future
  /// would never complete and the profile would never arrive nor be given up on.
  static Future<PlayerProfile?> playerProfile() async {
    if (!supported || !_signedIn) return null;
    PlayerData? player;
    try {
      player = await GamesServices.player.first
          .timeout(const Duration(seconds: 5), onTimeout: () => null);
    } catch (e) {
      // Not authenticated after all, or no plugin host. Either way the screen
      // falls back to its own title and a placeholder avatar.
      debugPrint('Player profile unavailable: $e');
      return null;
    }
    if (player == null) return null;
    final name = player.displayName.trim();
    return PlayerProfile(
      name: name.isEmpty ? null : name,
      icon: _decodeIcon(player.iconImage),
    );
  }

  /// The avatar, from base64 to bytes.
  ///
  /// Forgiving on the way in because the encoding is the platform's to choose:
  /// the plugin already strips newlines from what Android sends, and a data URI
  /// prefix costs nothing to tolerate. A picture that will not decode is a
  /// missing picture, never a broken screen.
  static Uint8List? _decodeIcon(String? encoded) {
    if (encoded == null || encoded.isEmpty) return null;
    var data = encoded.replaceAll(RegExp(r'\s'), '');
    if (data.startsWith('data:')) {
      final comma = data.indexOf(',');
      if (comma == -1) return null;
      data = data.substring(comma + 1);
    }
    try {
      return base64Decode(data);
    } catch (e) {
      debugPrint('Player icon undecodable: $e');
      return null;
    }
  }

  /// How many achievements the player has unlocked, out of how many the
  /// platform knows about. Null when it will not say.
  ///
  /// The platform is the authority here rather than this app: an achievement
  /// unlocked on another device, or before a reinstall, is still unlocked, and
  /// nothing local remembers that. Deliberately not force-refreshed — the
  /// cached answer is what the player just saw on the achievements screen, and
  /// a stale badge count is a far smaller thing than a screen that waits on the
  /// network to draw a number.
  static Future<(int unlocked, int total)?> achievementProgress() async {
    if (!supported || !_signedIn) return null;
    try {
      final items = await Achievements.loadAchievements(ignoreImages: true)
          .timeout(const Duration(seconds: 8), onTimeout: () => null);
      if (items == null || items.isEmpty) return null;
      return (items.where((a) => a.unlocked).length, items.length);
    } catch (e) {
      debugPrint('Achievements unreadable: $e');
      return null;
    }
  }

  /// How many achievements Dotto defines, for the screens that need a
  /// denominator before the platform has given them one.
  static int get achievementCount => _worldAchievements.length + 3;

  /// What to call the games service in text the player reads.
  static String get platformName {
    if (kIsWeb) return 'game services';
    return Platform.isAndroid ? 'Play Games' : 'Game Center';
  }

  /// How long to wait for a sign-in before giving up on it.
  ///
  /// Deliberately generous, because the clock covers the player as much as the
  /// platform: Game Center's sheet can ask for an Apple Account password, and a
  /// short deadline would fail a sign-in that was about to succeed.
  ///
  /// It exists at all because [GamesServices.signIn] is not guaranteed to
  /// complete. The iOS side hands its result to GameKit's authenticate handler
  /// and answers nothing until that handler fires, and where there is no account
  /// to authenticate against, GameKit calls it with neither a view controller nor
  /// an error: the future then stays pending for the life of the process. A
  /// simulator with no Apple Account does this, and so does Game Center switched
  /// off under Screen Time. Every other platform call in this file already had a
  /// deadline for the same reason; this one did not, and what waited on it was
  /// the spinner on the onboarding screen, with both of that screen's buttons
  /// disabled behind it.
  static const _signInDeadline = Duration(seconds: 90);

  /// Make sure there is an account, asking for one if there is not.
  ///
  /// The only place [GamesServices.signIn] is called from, and it may show the
  /// platform's own dialog — so every caller must be a player action: the Sign
  /// In button on the onboarding screen, or Achievements. Nothing on the launch
  /// path may call this.
  ///
  /// The result of [GamesServices.signIn] is the answer, and the only one worth
  /// having. Both platforms report success only once the player is genuinely
  /// authenticated — Play Games checks `isAuthenticated` and loads the player
  /// before returning, Game Center returns through its authenticate handler —
  /// and both raise a [PlatformException] otherwise.
  ///
  /// Asking [GamesServices.isSignedIn] afterwards to confirm it, as this used
  /// to, could only ever make the answer worse: it is a fresh event-channel
  /// round trip that reports "no" for a slow player fetch or a dropped network,
  /// so a sign-in the player had just completed came back false and Achievements
  /// asked them to sign in again. There is no re-check here now.
  ///
  /// No pre-check either: [GamesServices.signIn] on an already-authenticated
  /// player returns success without showing anything, so the probe bought
  /// nothing and could hang.
  ///
  /// Bounded by [_signInDeadline], like every other platform call here.
  static Future<bool> ensureSignedIn() async {
    if (!supported) return false;
    if (_signedIn) return true;
    try {
      // The deadline abandons the call rather than cancelling it: the platform
      // side carries on, and a sign-in that lands after it is simply not
      // credited. That is recoverable rather than wrong: a later ensureSignedIn
      // finds the authenticate handler already installed and an authenticated
      // player behind it, and returns success at once.
      await GamesServices.signIn().timeout(_signInDeadline);
    } catch (e) {
      // Cancelled, no Play Services, no network, or nothing answered at all.
      // All the same to the caller.
      debugPrint('Game services sign-in failed: $e');
      return false;
    }
    _setSignedIn(true);
    // A first sign-in is also the first chance to pull a cloud save.
    await CloudSaveService.load();
    return true;
  }

  /// How long to let a just-finished sign-in settle before asking the platform
  /// for a screen.
  ///
  /// [GamesServices.signIn] resolves the moment the account is authenticated,
  /// which on Android is while Play Games' own account picker is still coming
  /// down and this app's activity has not resumed. Asking for the achievements
  /// UI in that window is refused — the player signed in successfully and was
  /// then told to sign in. A beat is enough, and it is only paid on the tap
  /// that actually signed in.
  static const _postSignInSettle = Duration(milliseconds: 500);

  /// Open the platform's own achievements screen, signing in if needed.
  ///
  /// Returns false when it could not be shown — no games platform, sign-in
  /// declined, or the platform refused — so the caller can say something
  /// useful rather than leaving a tap that appears to do nothing. [signedIn]
  /// afterwards separates the two: true means there is an account and the
  /// screen itself would not open.
  static Future<bool> showAchievements() async {
    if (!supported) return false;
    if (await _openAchievements()) return true;
    // The remembered sign-in can outlive the account behind it — signing out of
    // the Play Games app is done from the Play Games app, and says nothing to
    // this one. A refusal here is the only notice given, so drop the flag and
    // try once more, properly. The retry is a real sign-in, which is allowed:
    // this is a tap on Achievements, not a launch.
    _setSignedIn(false);
    return _openAchievements();
  }

  /// One attempt: have an account, then show the screen.
  static Future<bool> _openAchievements() async {
    final hadAccount = _signedIn;
    if (!await ensureSignedIn()) return false;
    if (!hadAccount) await Future<void>.delayed(_postSignInSettle);
    try {
      await GamesServices.showAchievements();
      return true;
    } catch (e) {
      debugPrint('Could not show achievements: $e');
      return false;
    }
  }

  static void _unlock(_Ach ach) {
    if (!supported || !_signedIn) return;
    // Sending a blank id would be an error report per achievement, several
    // times a level. Every id is filled in now, so this only ever fires if one
    // is removed again.
    if (ach.forPlatform.isEmpty) return;
    unawaited(
      GamesServices.unlock(
        achievement: Achievement(
          androidID: ach.android,
          iOSID: ach.ios,
          percentComplete: 100,
        ),
      ).catchError((Object e) {
        debugPrint('Achievement unlock failed: $e');
        return null;
      }),
    );
  }

  /// Called after a level is recorded as complete.
  ///
  /// [completed] is the full set of finished levels, [world] the world the
  /// level just won belongs to, and [worldFinished] whether that world is now
  /// complete. The caller works those out because it already holds the level
  /// data; this class deliberately knows nothing about level numbering.
  static void onLevelCompleted({
    required int world,
    required bool worldFinished,
    required int totalCompleted,
    required int levelCount,
    required int lifetimeHints,
  }) {
    if (!supported) return;

    _sessionCompletions++;
    if (_sessionCompletions >= kSpeedRunnerTarget) _unlock(_speedRunner);

    if (worldFinished) {
      final ach = _worldAchievements[world];
      if (ach != null) _unlock(ach);
    }
    if (totalCompleted >= levelCount) _unlock(_master);
    if (lifetimeHints >= kHintSeekerTarget) _unlock(_hintSeeker);
  }

  /// Hints are taken outside a level completion too, so this is checked on its
  /// own as well — otherwise the badge would wait for the next level to end.
  static void onHintUsed(int lifetimeHints) {
    if (lifetimeHints >= kHintSeekerTarget) _unlock(_hintSeeker);
  }

  /// Tests only.
  @visibleForTesting
  static void resetForTest({bool prompted = false}) {
    _sessionCompletions = 0;
    _signedIn = false;
    _prompted = prompted;
    _prefs = null;
  }

  /// Tests only: every (iOS, Android) id pair the game can report.
  @visibleForTesting
  static List<(String, String)> get allIds => [
        for (final a in _worldAchievements.values) (a.ios, a.android),
        (_master.ios, _master.android),
        (_hintSeeker.ios, _hintSeeker.android),
        (_speedRunner.ios, _speedRunner.android),
      ];

  /// Tests only: whether Android is switched on yet.
  @visibleForTesting
  static bool get androidReady => _androidReady;

  /// Tests only: the sign-in deadline. Exposed so its existence can be asserted
  /// rather than trusted, since the state it guards against cannot be reached
  /// from a test: `supported` is false under `flutter test`, so [ensureSignedIn]
  /// returns before it would ever wait on the platform.
  @visibleForTesting
  static Duration get signInDeadline => _signInDeadline;
}
