// Game Center on iOS, Play Games Services on Android.
//
// Both platforms are wired up. The iOS column holds the reverse-domain ids
// registered in App Store Connect, the Android column the generated Play
// Console ones, and all ten exist on both sides.
//
// The plugin's Achievement.id returns androidID on Android, so a blank one
// would hand Play Games an empty achievement id. [_unlock] still refuses to
// send one, which is now a safety net against a half-filled table rather than
// the state the app ships in.
//
// Everything here is optional and fire-and-forget. A player who never signs in,
// declines Game Center, or plays offline must see no difference in the game, so
// nothing is awaited from game code and every call swallows its errors. An
// achievement is a nice thing that happens, never a thing that can fail.

import 'dart:async';
import 'dart:io' show Platform;

import 'package:flutter/foundation.dart';
import 'package:games_services/games_services.dart';
import 'package:shared_preferences/shared_preferences.dart';

import 'cloud_save_service.dart';

/// The achievements Dotto reports, with their per-platform ids.
///
/// iOS uses the reverse-domain ids registered in App Store Connect. The Android
/// column is filled in from the Play Console, where ids look like
/// `CgkI...ABw` — they are generated, not chosen, so they cannot be written
/// ahead of the console work.
class _Ach {
  const _Ach(this.ios, this.android);

  final String ios;
  final String android;

  String get forPlatform => Platform.isAndroid ? android : ios;
}

// The Android ids are generated by Play Console and are meaningless to read —
// they differ only in their last character or two, so a transposition here
// would silently unlock the wrong badge rather than fail. Kept in the same
// order as the worlds for that reason, and covered by a test that checks they
// are all distinct.
const _worldAchievements = <int, _Ach>{
  1: _Ach('com.karimkod.dotto.world1', 'CgkIq9GejqIREAIQAA'),
  2: _Ach('com.karimkod.dotto.world2', 'CgkIq9GejqIREAIQAQ'),
  3: _Ach('com.karimkod.dotto.world3', 'CgkIq9GejqIREAIQAg'),
  4: _Ach('com.karimkod.dotto.world4', 'CgkIq9GejqIREAIQAw'),
  5: _Ach('com.karimkod.dotto.world5', 'CgkIq9GejqIREAIQBA'),
  6: _Ach('com.karimkod.dotto.world6', 'CgkIq9GejqIREAIQBQ'),
  7: _Ach('com.karimkod.dotto.world7', 'CgkIq9GejqIREAIQBg'),
};

const _master = _Ach('com.karimkod.dotto.master', 'CgkIq9GejqIREAIQBw');
const _hintSeeker = _Ach('com.karimkod.dotto.hint_seeker', 'CgkIq9GejqIREAIQCA');
const _speedRunner = _Ach('com.karimkod.dotto.speed_runner', 'CgkIq9GejqIREAIQCQ');

/// Hints taken across all sessions before "Hint Seeker" unlocks.
const int kHintSeekerTarget = 10;

/// Levels finished in one sitting before "Speed Runner" unlocks.
const int kSpeedRunnerTarget = 5;

class GameServices {
  GameServices._();

  /// Whether the Android side is configured well enough to sign in.
  ///
  /// True since the Play Games application id landed in AndroidManifest.xml
  /// (as `@string/app_id`, defined in res/values/games-ids.xml). That entry is
  /// what this gate was waiting for: the SDK fails as it starts without one,
  /// natively, which the try/catch around [ensureSignedIn] would not contain.
  ///
  /// If Android sign-in ever needs disabling in a hurry — a crash on some
  /// device, a Play Console misconfiguration — setting this back to false is
  /// the switch, and costs nothing but the achievements.
  static const bool _androidReady = true;

  /// Where a games platform exists to talk to. Web has none, and `flutter test`
  /// has no plugin host.
  static bool get supported {
    if (kIsWeb) return false;
    if (Platform.environment.containsKey('FLUTTER_TEST')) return false;
    if (Platform.isAndroid) return _androidReady;
    return Platform.isIOS;
  }

  static bool _signedIn = false;
  static bool get signedIn => _signedIn;

  /// Whether the onboarding sign-in offer has been made.
  ///
  /// Asked once, on a first launch, and never again: a player who declined has
  /// answered, and asking each launch is how an optional feature turns into a
  /// nuisance. Settings → Achievements is the way back in.
  static const _promptedKey = 'sign_in_prompted';
  static SharedPreferences? _prefs;
  static bool _prompted = false;

  /// Whether onboarding should offer to sign in. False once asked, once signed
  /// in, or where there is no games platform to sign in to.
  static bool get needsSignInPrompt => supported && !_prompted && !_signedIn;

  /// Load the "already asked" flag. Call before the first frame.
  static Future<void> init() async {
    try {
      final prefs = _prefs = await SharedPreferences.getInstance();
      _prompted = prefs.getBool(_promptedKey) ?? false;
    } catch (_) {
      // No storage. The offer may be made twice, which is a nuisance rather
      // than a fault.
    }
  }

  /// Remember that the offer was made — whatever the player answered.
  static void markSignInPrompted() {
    _prompted = true;
    final prefs = _prefs;
    if (prefs == null) return;
    unawaited(prefs.setBool(_promptedKey, true).catchError((_) => false));
  }

  /// Levels finished since launch, for Speed Runner. Not persisted — the
  /// achievement is about one sitting.
  static int _sessionCompletions = 0;

  /// Pick up an account that already exists, without asking for one.
  ///
  /// Deliberately not a sign-in: it only reads the current state. Signing in is
  /// something the player does — from the onboarding offer or from Achievements
  /// — and a launch that raises the platform's sign-in dialog on its own is the
  /// bug this replaced. Reading the state still matters, because a returning
  /// player who signed in on a previous launch should keep earning achievements
  /// and syncing saves without being asked anything.
  static Future<void> restoreSignInState() async {
    if (!supported) return;
    try {
      _signedIn = await GamesServices.isSignedIn;
    } catch (e) {
      debugPrint('Game services state unreadable, achievements off: $e');
      return;
    }
    // Saved games are per-account, so the cloud is only reachable once there is
    // an account. This is the earliest honest moment to pull it.
    if (_signedIn) await CloudSaveService.load();
  }

  /// What to call the games service in text the player reads.
  static String get platformName {
    if (kIsWeb) return 'game services';
    return Platform.isAndroid ? 'Play Games' : 'Game Center';
  }

  /// Make sure there is an account, asking for one if there is not.
  ///
  /// The only place [GamesServices.signIn] is called from, and it may show the
  /// platform's own dialog — so every caller must be a player action: the Sign
  /// In button on the onboarding screen, or Achievements. Nothing on the launch
  /// path may call this.
  static Future<bool> ensureSignedIn() async {
    if (!supported) return false;
    if (_signedIn) return true;
    try {
      // Cheap re-check first — signing in may have happened outside the game.
      if (await GamesServices.isSignedIn) {
        _signedIn = true;
        return true;
      }
      await GamesServices.signIn();
      _signedIn = await GamesServices.isSignedIn;
      // A first sign-in is also the first chance to pull a cloud save.
      if (_signedIn) await CloudSaveService.load();
      return _signedIn;
    } catch (e) {
      // Cancelled, no Play Services, no network. All the same to the caller.
      debugPrint('Game services sign-in failed: $e');
      return false;
    }
  }

  /// Open the platform's own achievements screen, signing in if needed.
  ///
  /// Returns false when it could not be shown — no games platform, sign-in
  /// declined, or the platform refused — so the caller can say something
  /// useful rather than leaving a tap that appears to do nothing.
  static Future<bool> showAchievements() async {
    if (!supported) return false;
    if (!await ensureSignedIn()) return false;
    try {
      await GamesServices.showAchievements();
      return true;
    } catch (e) {
      debugPrint('Could not show achievements: $e');
      return false;
    }
  }

  static void _unlock(_Ach ach) {
    if (!supported || !_signedIn) return;
    // Sending a blank id would be an error report per achievement, several
    // times a level. Every id is filled in now, so this only ever fires if one
    // is removed again.
    if (ach.forPlatform.isEmpty) return;
    unawaited(
      GamesServices.unlock(
        achievement: Achievement(
          androidID: ach.android,
          iOSID: ach.ios,
          percentComplete: 100,
        ),
      ).catchError((Object e) {
        debugPrint('Achievement unlock failed: $e');
        return null;
      }),
    );
  }

  /// Called after a level is recorded as complete.
  ///
  /// [completed] is the full set of finished levels, [world] the world the
  /// level just won belongs to, and [worldFinished] whether that world is now
  /// complete. The caller works those out because it already holds the level
  /// data; this class deliberately knows nothing about level numbering.
  static void onLevelCompleted({
    required int world,
    required bool worldFinished,
    required int totalCompleted,
    required int levelCount,
    required int lifetimeHints,
  }) {
    if (!supported) return;

    _sessionCompletions++;
    if (_sessionCompletions >= kSpeedRunnerTarget) _unlock(_speedRunner);

    if (worldFinished) {
      final ach = _worldAchievements[world];
      if (ach != null) _unlock(ach);
    }
    if (totalCompleted >= levelCount) _unlock(_master);
    if (lifetimeHints >= kHintSeekerTarget) _unlock(_hintSeeker);
  }

  /// Hints are taken outside a level completion too, so this is checked on its
  /// own as well — otherwise the badge would wait for the next level to end.
  static void onHintUsed(int lifetimeHints) {
    if (lifetimeHints >= kHintSeekerTarget) _unlock(_hintSeeker);
  }

  /// Tests only.
  @visibleForTesting
  static void resetForTest({bool prompted = false}) {
    _sessionCompletions = 0;
    _signedIn = false;
    _prompted = prompted;
    _prefs = null;
  }

  /// Tests only: every (iOS, Android) id pair the game can report.
  @visibleForTesting
  static List<(String, String)> get allIds => [
        for (final a in _worldAchievements.values) (a.ios, a.android),
        (_master.ios, _master.android),
        (_hintSeeker.ios, _hintSeeker.android),
        (_speedRunner.ios, _speedRunner.android),
      ];

  /// Tests only: whether Android is switched on yet.
  @visibleForTesting
  static bool get androidReady => _androidReady;
}
