// Firebase project configuration for the Dotto app (project dotto-d817e).
//
// Normally generated by `flutterfire configure`; written by hand here because
// the CLI cannot run in this environment. The values match
// android/app/google-services.json and ios/Runner/GoogleService-Info.plist, and
// all three have to be changed together — a mismatch between the Dart options
// and the native config is the kind of fault that shows up as "analytics is
// silent" rather than as an error.
//
// None of this is secret. A Firebase API key identifies the project to Google;
// it does not authorise anything on its own, which is why these files are
// normally committed. What guards the project is its security rules and App
// Check, not the secrecy of this key.
//
// Not secret does not mean not real. The key written here by hand was one the
// project had never issued, and every keyed call was refused with
// API_KEY_SERVICE_BLOCKED — which reads like a restriction problem and is not
// one. Android and iOS carried the same string, which is itself the tell:
// Firebase issues a separate key per platform, so one key across both means it
// was invented rather than copied. Take these from
// `gcloud services api-keys list --project=dotto-d817e` and get-key-string, or
// from the console; never type one that looks plausible.
//
// Web is absent deliberately: Analytics.supported returns false there, so no
// web app was registered and currentPlatform throws rather than pretending.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtOOpHb9gg5JrU0mrWBBqo7LqULO0Um0g',
    appId: '1:593272219819:android:c37f7e29ba239433adafee',
    messagingSenderId: '593272219819',
    projectId: 'dotto-d817e',
    storageBucket: 'dotto-d817e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBdhtUHhSZNwojDsQuA-ua_yJ4B61fpR98',
    appId: '1:593272219819:ios:cdef52c41ffe61d9adafee',
    messagingSenderId: '593272219819',
    projectId: 'dotto-d817e',
    storageBucket: 'dotto-d817e.firebasestorage.app',
    iosBundleId: 'com.karimkod.dotto',
  );
}
